name: Kristov Atlas
description: Information security (InfoSec), Application Security (AppSec), Bitcoin security and privacy content
url: https://kristovatlas.github.io/
markdown: rdiscount
highlighter: pygments
